
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NYC_Taxi_System.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DriverAvailability
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DriverAvailability()
    {

        this.DriverStatusCounts = new HashSet<DriverStatusCount>();

    }


    public string Driver { get; set; }

    public bool Status { get; set; }



    public virtual User User { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DriverStatusCount> DriverStatusCounts { get; set; }

}

}
