
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NYC_Taxi_System.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DriverVehicle
{

    public string Driver { get; set; }

    public int Type { get; set; }

    public int Seats { get; set; }

    public string Brand { get; set; }

    public string VRN { get; set; }

    public string LicenseNumber { get; set; }

    public string InsuranceNumber { get; set; }

    public string NIC { get; set; }



    public virtual User User { get; set; }

    public virtual VehicleType VehicleType { get; set; }

}

}
