
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NYC_Taxi_System.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Reservation
{

    public int Reservation_Id { get; set; }

    public string Passenger { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Phone { get; set; }

    public System.DateTime PickUpDate { get; set; }

    public System.TimeSpan PickUpTime { get; set; }

    public int Vehicle { get; set; }

    public string PickUpStreetNo { get; set; }

    public string PickUpRoute { get; set; }

    public string PickUpCity { get; set; }

    public string PickUpProvince { get; set; }

    public string PickUpZipCode { get; set; }

    public string DropStreetNo { get; set; }

    public string DropRoute { get; set; }

    public string DropCity { get; set; }

    public string DropProvince { get; set; }

    public string DropZipCode { get; set; }

    public string Driver { get; set; }

    public string Status { get; set; }

    public decimal PickUpLat { get; set; }

    public decimal PickUpLng { get; set; }

    public decimal Charge { get; set; }

    public decimal OnHireDistance { get; set; }

    public Nullable<decimal> OverallDistance { get; set; }



    public virtual WaitingTime WaitingTime { get; set; }

    public virtual User User_Driver { get; set; }

    public virtual User User_Passenger { get; set; }

    public virtual VehicleType VehicleType { get; set; }

    public virtual Feedback Feedback { get; set; }

}

}
