
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NYC_Taxi_System.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.Reservations_Driver = new HashSet<Reservation>();

        this.Reservations_Passenger = new HashSet<Reservation>();

        this.Feedbacks = new HashSet<Feedback>();

    }


    public string Username { get; set; }

    public string UserType { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public bool IsEmailVerified { get; set; }

    public Nullable<System.Guid> ActivationCode { get; set; }

    public Nullable<System.Guid> ResetPasswordCode { get; set; }



    public virtual DriverAvailability DriverAvailability { get; set; }

    public virtual DriverLocation DriverLocation { get; set; }

    public virtual DriverVehicle DriverVehicle { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reservation> Reservations_Driver { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reservation> Reservations_Passenger { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Feedback> Feedbacks { get; set; }

}

}
