
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NYC_Taxi_System.Models
{

using System;
    using System.Collections.Generic;
    
public partial class WaitingTime
{

    public int Id { get; set; }

    public Nullable<System.DateTime> StartTime { get; set; }

    public Nullable<int> Duration { get; set; }

    public bool Status { get; set; }



    public virtual Reservation Reservation { get; set; }

}

}
